Main app
beyond-io/StuDash pull request #37
Opened 2020-12-07 10:07 UTC by or313

This PR complete the work on #32 which is adding the main app and base template for the project.
This main app will eventually include all the features which we intend to develop
fix #32

2020-12-08 15:43 UTC, lioramilbaum requested changes
Same request as in #36 
Link an issue and a descriptive target

2020-12-08 21:23 UTC, ravidbro commented
The branch has conflicts, please rebase and fix the conflicts

2020-12-08 21:30 UTC, ravidbro commented
also, the issue doesn't seem to be linked (in the right pane), use the word 'fix'.
you can see an example in https://github.com/beyond-io/StuDash/pull/38

2020-12-09 09:18 UTC, simzacks reviewed
I recommend that you add something to the css file before uploading it. Having a blank file that _may be_ used in the future is bad form.

2020-12-09 09:18 UTC, simzacks commented on StuDash/settings.py
> +    "django.contrib.sites",
django.contrib.sites is for hosting multiple sites with one backend. Are you planning on doing this? if not, do you have another reason for using this?

2020-12-09 09:18 UTC, simzacks commented on StuDash/settings.py
> +    "main",
you might want to call your application studash, instead of "main"

2020-12-09 09:18 UTC, simzacks commented on StuDash/settings.py
> +if DISABLE_USERNAME:
This doesn't look like a setting that you will change back and forth. This is the type of setting that is used for applications with multiple installations that you want to give the sysadmin some options. However, for a small project like this it is very extra.
Try to develop minimally.

2020-12-09 09:18 UTC, simzacks commented on content/assets/js/ie10-viewport-bug-workaround.js
> +  if (navigator.userAgent.match(/IEMobile\/10\.0/)) {
I would suggest that for the MVP you make sure it works with one browser and only write code that will work for that. In the future if you want to expand you can verify the GUI on multiple browsers.

2020-12-09 09:18 UTC, simzacks commented on content/templates/main/change_language.html
> +    <h4>{% trans 'Change language' %}</h4>
Are multiple languages part of your MVP? That is generally considered an advanced feature.

2020-12-09 09:18 UTC, simzacks commented on content/templates/layouts/default/page.html
> +    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
Your (empty) css file is not in the content/static/css folder. Will this work?

2020-12-09 09:18 UTC, ravidbro approved these changes

2020-12-09 09:19 UTC, merged