explanation on StuDash
beyond-io/StuDash pull request #8
Opened 2020-11-11 18:53 UTC by nofarda

2020-11-11 22:16 UTC, ravidbro requested changes
The content is good.
You need to link the PR to an issue.
This is ".md " file that supports formatting, look at how the file looks like in the rich view with formatting and align it.

2020-11-12 06:50 UTC, ifireball commented
Please add a more detailed PR description

2020-11-12 11:51 UTC, Noa-Git commented
Fixes #6

2020-11-12 12:40 UTC, ravidbro commented
> Fixes #6

For update like this, it's better to update the description of the PR and not as a comment

2020-11-12 19:08 UTC, ravidbro commented
Please format it with .md syntax and look that the look makes sense.
You can see about the syntax here: https://guides.github.com/features/mastering-markdown/
You can also use: https://dillinger.io/

2020-11-14 20:53 UTC, ravidbro requested changes

2020-11-14 20:53 UTC, ravidbro commented on README.md
> +[ofek App](https://www.easyform.co.il/SystemFiles/242/Ofek.jpg)
Embedding images can be problematic legally. 
Please put a link to a web page on the site or remove it from here.

2020-11-14 21:05 UTC, ravidbro commented
Why did you add 'StuDash' files in this PR?
It's not needed for updating the ReadMe, and also it creates a conflict

2020-11-14 21:06 UTC, ravidbro commented
Ensure that the PR has only one commit for such a change of one file at the end of the fix.

2020-11-14 22:34 UTC, ravidbro commented on README.md
> +[ofek App](https://www.easyform.co.il/SystemFiles/242/Ofek.jpg)
I meant removing to removing the link to the png file, not removing the README

2020-11-14 23:17 UTC, Gal-f commented
I'm closing this PR and sent a new one with the same content at #14.
This is due to some errors we weren't able the resolve thus far.

2020-11-14 23:17 UTC, closed without merging